import type { IssuerCredentialGroup } from "@/app/services/types";

export const COMING_SOON_CREDENTIALS: IssuerCredentialGroup[] = [
  {
    issuer: "Base",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "NFT Collections: Total Created",
        slug: "base_nft_collections_total_created",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "NFT Collections: Unique Holders",
        slug: "base_nft_collections_unique_holders",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "NFT Collections: Market Cap",
        slug: "base_nft_collections_market_cap",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "X/Twitter",
    total: 0,
    max_total: 0,
    points: [
      // Add credentials here as needed, with slug
      {
        label: "Kaito Yaps Airdrop",
        slug: "kaito_airdrop_one",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Flaunch",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Coin Earnings",
        slug: "flaunch_earnings",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Coop Records",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Music Earnings",
        slug: "coop_records_earnings",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Unique Collectors",
        slug: "coop_reords_holders",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Paragraph",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Creator Rewards",
        slug: "paragraph_creator_rewards",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Unique Collectors",
        slug: "paragraph_unique_collectors",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Total Posts",
        slug: "paragraph_total_posts",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Mirror",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Total Mints",
        slug: "mirror_total_mints",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Total Posts",
        slug: "mirror_total_posts",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      // Removed 'Unique Collectors' from Mirror
    ],
  },
  {
    issuer: "Phi",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Artist Score",
        slug: "phi_artist_score",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Noice",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Tip Earnings",
        slug: "noice_tips_earnings",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Pods",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Creator Rewards",
        slug: "pods_creator_rewards",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Zora",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Coin Earnings",
        slug: "zora_coin_earnings",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Total Posts",
        slug: "zora_posts_coins",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Unique Holders",
        slug: "zora_unique_holders",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Coin Volume",
        slug: "zora_coin_volume",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Market Cap",
        slug: "zora_market_cap",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
  {
    issuer: "Lens",
    total: 0,
    max_total: 0,
    points: [
      {
        label: "Bonsai Airdrop #1",
        slug: "bonsai_airdrop",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
      {
        label: "Total Earnings",
        slug: "lens_total_earnings",
        value: 0,
        max_score: null,
        readable_value: null,
        uom: null,
        external_url: null,
      },
    ],
  },
];
