import {
  Trophy,
  Globe,
  MessageSquare,
  DollarSign,
  FileText,
  Users,
  Calendar,
  PenTool,
  Music,
  Mic,
  Palette,
  MessageCircle,
  Coins,
  Clock,
  Gift,
  Zap,
  Link,
  type LucideIcon,
} from "lucide-react";

export interface BadgeItem {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  completed: boolean;
  actionUrl?: string;
}

export interface BadgeSection {
  id: string;
  title: string;
  badges: BadgeItem[];
}

// Mock data for all badge categories
export const mockBadgeData: BadgeSection[] = [
  {
    id: "creator-score",
    title: "Creator Score",
    badges: [
      {
        id: "level-1",
        name: "Level 1",
        description: "Reach Creator Score Level 1",
        icon: Trophy,
        completed: true,
      },
      {
        id: "level-2",
        name: "Level 2",
        description: "Reach Creator Score Level 2",
        icon: Trophy,
        completed: true,
      },
      {
        id: "level-3",
        name: "Level 3",
        description: "Reach Creator Score Level 3",
        icon: Trophy,
        completed: false,
      },
      {
        id: "level-4",
        name: "Level 4",
        description: "Reach Creator Score Level 4",
        icon: Trophy,
        completed: false,
      },
      {
        id: "level-5",
        name: "Level 5",
        description: "Reach Creator Score Level 5",
        icon: Trophy,
        completed: false,
      },
      {
        id: "level-6",
        name: "Level 6",
        description: "Reach Creator Score Level 6",
        icon: Trophy,
        completed: false,
      },
    ],
  },
  {
    id: "platforms",
    title: "Platforms",
    badges: [
      {
        id: "x",
        name: "X",
        description: "Connect your X account and have followers",
        icon: MessageSquare,
        completed: true,
      },
      {
        id: "zora",
        name: "Zora",
        description: "Connect your Zora account and have collectors",
        icon: Globe,
        completed: false,
      },
      {
        id: "farcaster",
        name: "Farcaster",
        description: "Connect your Farcaster account and have followers",
        icon: MessageCircle,
        completed: true,
      },
      {
        id: "mirror",
        name: "Mirror",
        description: "Connect your Mirror account and have followers",
        icon: Link,
        completed: false,
      },
      {
        id: "paragraph",
        name: "Paragraph",
        description: "Connect your Paragraph account and have followers",
        icon: FileText,
        completed: false,
      },
      {
        id: "lens",
        name: "Lens",
        description: "Connect your Lens account and have followers",
        icon: Globe,
        completed: false,
      },
    ],
  },
  {
    id: "milestones",
    title: "Milestones",
    badges: [
      {
        id: "100-followers",
        name: "100 Followers",
        description: "Reach 100 followers across all platforms",
        icon: Users,
        completed: true,
      },
      {
        id: "1k-followers",
        name: "1K Followers",
        description: "Reach 1,000 followers across all platforms",
        icon: Users,
        completed: true,
      },
      {
        id: "10k-followers",
        name: "10K Followers",
        description: "Reach 10,000 followers across all platforms",
        icon: Users,
        completed: false,
      },
      {
        id: "100k-followers",
        name: "100K Followers",
        description: "Reach 100,000 followers across all platforms",
        icon: Users,
        completed: false,
      },
      {
        id: "1m-followers",
        name: "1M Followers",
        description: "Reach 1,000,000 followers across all platforms",
        icon: Users,
        completed: false,
      },
      {
        id: "10-earnings",
        name: "$10 Earnings",
        description: "Earn $10 from your content",
        icon: DollarSign,
        completed: true,
      },
      {
        id: "100-earnings",
        name: "$100 Earnings",
        description: "Earn $100 from your content",
        icon: DollarSign,
        completed: false,
      },
      {
        id: "1k-earnings",
        name: "$1k Earnings",
        description: "Earn $1,000 from your content",
        icon: DollarSign,
        completed: false,
      },
      {
        id: "10k-earnings",
        name: "$10k Earnings",
        description: "Earn $10,000 from your content",
        icon: DollarSign,
        completed: false,
      },
      {
        id: "100k-earnings",
        name: "$100k Earnings",
        description: "Earn $100,000 from your content",
        icon: DollarSign,
        completed: false,
      },
      {
        id: "10-posts",
        name: "10 Posts",
        description: "Publish 10 posts",
        icon: FileText,
        completed: true,
      },
      {
        id: "100-posts",
        name: "100 Posts",
        description: "Publish 100 posts",
        icon: FileText,
        completed: true,
      },
      {
        id: "1k-posts",
        name: "1K Posts",
        description: "Publish 1,000 posts",
        icon: FileText,
        completed: false,
      },
      {
        id: "10k-posts",
        name: "10K Posts",
        description: "Publish 10,000 posts",
        icon: FileText,
        completed: false,
      },
      {
        id: "1-year-onchain",
        name: "1 Year Onchain",
        description: "Be active onchain for 1 year",
        icon: Calendar,
        completed: true,
      },
      {
        id: "2-years-onchain",
        name: "2 Years Onchain",
        description: "Be active onchain for 2 years",
        icon: Calendar,
        completed: true,
      },
      {
        id: "3-years-onchain",
        name: "3 Years Onchain",
        description: "Be active onchain for 3 years",
        icon: Calendar,
        completed: false,
      },
      {
        id: "4-years-onchain",
        name: "4 Years Onchain",
        description: "Be active onchain for 4 years",
        icon: Calendar,
        completed: false,
      },
      {
        id: "5-years-onchain",
        name: "5 Years Onchain",
        description: "Be active onchain for 5 years",
        icon: Calendar,
        completed: false,
      },
      {
        id: "10-years-onchain",
        name: "10 Years Onchain",
        description: "Be active onchain for 10 years",
        icon: Calendar,
        completed: false,
      },
    ],
  },
  {
    id: "media",
    title: "Media",
    badges: [
      {
        id: "writing",
        name: "Writing",
        description: "Publish written content",
        icon: PenTool,
        completed: true,
      },
      {
        id: "music",
        name: "Music",
        description: "Create and share music",
        icon: Music,
        completed: false,
      },
      {
        id: "podcast",
        name: "Podcast",
        description: "Host or appear on podcasts",
        icon: Mic,
        completed: false,
      },
      {
        id: "visual",
        name: "Visual",
        description: "Create visual art and content",
        icon: Palette,
        completed: true,
      },
      {
        id: "social",
        name: "Social",
        description: "Engage actively on social platforms",
        icon: MessageCircle,
        completed: true,
      },
      {
        id: "coin",
        name: "Coin",
        description: "Create or launch a token",
        icon: Coins,
        completed: false,
      },
    ],
  },
  {
    id: "streaks",
    title: "Streaks",
    badges: [
      {
        id: "2-weeks",
        name: "2 Weeks in a Row",
        description: "Publish posts for 2 consecutive weeks",
        icon: Calendar,
        completed: true,
      },
      {
        id: "3-weeks",
        name: "3 Weeks in a Row",
        description: "Publish posts for 3 consecutive weeks",
        icon: Calendar,
        completed: true,
      },
      {
        id: "4-weeks",
        name: "4 Weeks in a Row",
        description: "Publish posts for 4 consecutive weeks",
        icon: Calendar,
        completed: false,
      },
      {
        id: "5-weeks",
        name: "5 Weeks in a Row",
        description: "Publish posts for 5 consecutive weeks",
        icon: Calendar,
        completed: false,
      },
      {
        id: "6-weeks",
        name: "6 Weeks in a Row",
        description: "Publish posts for 6 consecutive weeks",
        icon: Calendar,
        completed: false,
      },
      {
        id: "7-weeks",
        name: "7 Weeks in a Row",
        description: "Publish posts for 7 consecutive weeks",
        icon: Calendar,
        completed: false,
      },
      {
        id: "2-months",
        name: "2 Months in a Row",
        description: "Publish posts for 2 consecutive months",
        icon: Clock,
        completed: false,
      },
      {
        id: "3-months",
        name: "3 Months in a Row",
        description: "Publish posts for 3 consecutive months",
        icon: Clock,
        completed: false,
      },
    ],
  },
  {
    id: "airdrops",
    title: "Airdrops",
    badges: [
      {
        id: "zora-airdrop",
        name: "Zora",
        description: "Participate in Zora airdrops",
        icon: Gift,
        completed: true,
      },
      {
        id: "kaito-airdrop",
        name: "Kaito",
        description: "Participate in Kaito airdrops",
        icon: Zap,
        completed: false,
      },
      {
        id: "bonsai-airdrop",
        name: "Bonsai",
        description: "Participate in Bonsai airdrops",
        icon: Gift,
        completed: false,
      },
    ],
  },
];
